Return-Path: <platform-driver-x86-owner@vger.kernel.org>
X-Original-To: lists+platform-driver-x86@lfdr.de
Delivered-To: lists+platform-driver-x86@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 8AF037566C
	for <lists+platform-driver-x86@lfdr.de>; Thu, 25 Jul 2019 19:59:49 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1727560AbfGYR7s (ORCPT
        <rfc822;lists+platform-driver-x86@lfdr.de>);
        Thu, 25 Jul 2019 13:59:48 -0400
Received: from mail-pl1-f196.google.com ([209.85.214.196]:45965 "EHLO
        mail-pl1-f196.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1726470AbfGYR7s (ORCPT
        <rfc822;platform-driver-x86@vger.kernel.org>);
        Thu, 25 Jul 2019 13:59:48 -0400
Received: by mail-pl1-f196.google.com with SMTP id y8so23705211plr.12;
        Thu, 25 Jul 2019 10:59:48 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:references:in-reply-to:from:date:message-id:subject:to
         :cc;
        bh=OZVrPWXD9IIoDuvUUXZFRARs0rzH7izNJWc43vWc8f4=;
        b=Rd8ooyBcixiJoSdqb4r+koekA7w+22f1EZInuRgGZayKsTImv57+nvVQYZL0danr+M
         Sds5eyhbJoV8JsxXcdzZX++mK9Yi6R2+Bf1WKE1xJCqXTbhdrUWWh8YhIecbkb+2m0RP
         pwO/WRRPmCQQF0eu384aTLqLaMfZYry2Ph1FBhxdaUEbgOJ97orEH1MWJtM7YrnZjeCm
         rbvXtV14AWqgCKY6M/bszS2GQ41hVOaITDg6NQjPT9ilbG0CP1EWTbAXXQKcAqcpB8tv
         x36I+qxqiPQ1XKCGhNPZm0pd8BprINbwRyiZBm+oY9oRzva4PaVWmy9KlPvGMgqPpy5s
         UZQg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:references:in-reply-to:from:date
         :message-id:subject:to:cc;
        bh=OZVrPWXD9IIoDuvUUXZFRARs0rzH7izNJWc43vWc8f4=;
        b=Gb6qo55LZCkJtfZO/A8qjI3WKr63QZp7ulvTE0Q/2J8eV//eJxk3BhEkMLhVqY+BRH
         hvfD64VpShOp3XD1tfubn3QUE87nzN5TxfxuO2fg3m1XMR0DlCcWNeZIDXGl+mD3Ysp1
         EQipOJNqxpWTH1brE1Co4E4zRCFQ4ooBtCNggsVr0EAh6SBCAjiWh0XgcgDZsbEhlNv6
         GczPILFjIRVai+L2MZSjUOYmzDIvK2xuIpCB8VCEkyjivDr+5UrutwMauKYDiGE0P9/C
         E7hKwBvz6YPQpLlgW1kWOiyHKvAKOLBIU6B7eXIVF7zRn1kAAGXefhsJoEjprLLMLHT2
         /8Uw==
X-Gm-Message-State: APjAAAV8zCMU70BVaR7Z6buCUuvYuK4GdRYHwjaoP0EIpcI7TOzThTGI
        ZQ1LbJYM/I+aW8fpgg6UrgHCIqvuCoFGLnKXsIo=
X-Google-Smtp-Source: APXvYqxoh8QwPJMI7vKxro0n0V1xubdW18NnEkgOBlXrTK6uAoXnZDlvo1y3YNW/+KWGJ4bcY3HtmR01RBWmVWAZF98=
X-Received: by 2002:a17:902:9349:: with SMTP id g9mr90593495plp.262.1564077587755;
 Thu, 25 Jul 2019 10:59:47 -0700 (PDT)
MIME-Version: 1.0
References: <20190724081415.8926-1-rhyskidd@gmail.com> <20190724081415.8926-2-rhyskidd@gmail.com>
In-Reply-To: <20190724081415.8926-2-rhyskidd@gmail.com>
From:   Andy Shevchenko <andy.shevchenko@gmail.com>
Date:   Thu, 25 Jul 2019 20:59:36 +0300
Message-ID: <CAHp75VcRDVBhSbYkUBy7cWCo7LPJD2OYZb3_mQ9jbJuNyDFjCQ@mail.gmail.com>
Subject: Re: [PATCH 2/3] platform/x86: dell-wmi: Ignore keyboard backlight
 change KBD_LED_AUTO_TOKEN
To:     Rhys Kidd <rhyskidd@gmail.com>
Cc:     Matthew Garrett <mjg59@google.com>,
        =?UTF-8?Q?Pali_Roh=C3=A1r?= <pali.rohar@gmail.com>,
        Darren Hart <dvhart@infradead.org>,
        Andy Shevchenko <andy@infradead.org>,
        Platform Driver <platform-driver-x86@vger.kernel.org>,
        Linux Kernel Mailing List <linux-kernel@vger.kernel.org>
Content-Type: text/plain; charset="UTF-8"
Sender: platform-driver-x86-owner@vger.kernel.org
Precedence: bulk
List-ID: <platform-driver-x86.vger.kernel.org>
X-Mailing-List: platform-driver-x86@vger.kernel.org

On Wed, Jul 24, 2019 at 11:14 AM Rhys Kidd <rhyskidd@gmail.com> wrote:
>
> There's a wmi event generated by dell-wmi when pressing keyboard backlight
> toggle key:
> [1224178.355650] dell_wmi: Unknown key with type 0x0011 and code 0x01e3 pressed
>
> This event is for notification purposes, let's ignore it.
>

Pushed to my review and testing queue, thanks!


> Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>
> ---
>  drivers/platform/x86/dell-wmi.c | 1 +
>  1 file changed, 1 insertion(+)
>
> diff --git a/drivers/platform/x86/dell-wmi.c b/drivers/platform/x86/dell-wmi.c
> index ae331ac119a1..68a8a4eba4e3 100644
> --- a/drivers/platform/x86/dell-wmi.c
> +++ b/drivers/platform/x86/dell-wmi.c
> @@ -313,6 +313,7 @@ static const struct key_entry dell_wmi_keymap_type_0011[] = {
>         /* Keyboard backlight level changed */
>         { KE_IGNORE, 0x01e1, { KEY_RESERVED } },
>         { KE_IGNORE, 0x01e2, { KEY_RESERVED } },
> +       { KE_IGNORE, 0x01e3, { KEY_RESERVED } },
>         { KE_IGNORE, 0x02ea, { KEY_RESERVED } },
>         { KE_IGNORE, 0x02eb, { KEY_RESERVED } },
>         { KE_IGNORE, 0x02ec, { KEY_RESERVED } },
> --
> 2.20.1
>


-- 
With Best Regards,
Andy Shevchenko
